# sample azure pipelie


trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
    - task: AzureCloudPowerShellDeployment@1
      inputs:
        EnableAdvancedStorageOptions: false
        CsPkg: 
        slotName: 'Production'
        AllowUpgrade: true
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
